easy_flask/data/project/server/models.py
# project/server/models.py


import datetime

from project.server import app, db, bcrypt


class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=True)
    password = db.Column(db.String(255), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    last_login = db.Column(db.DateTime, nullable=False)

    def __init__(self, **kwargs):
        self.username = kwargs.get('username')
        self.email = kwargs.get('email', None)
        self.password = bcrypt.generate_password_hash(
                        kwargs.get('password'), app.config.get('BCRYPT_LOG_ROUNDS'))
        self.registered_on = datetime.datetime.now()
        self.admin = kwargs.get('admin')
        self.last_login = datetime.datetime.now()

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def is_admin(self):
        return self.admin

    def __repr__(self):
        return '<User {0}>'.format(self.username)

easy_flask/data/project/server/user/forms.py
# project/server/user/forms.py


from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email

from project.server import db
from project.server.models import User


class LoginForm(Form):
    username = StringField('Username', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])

    def get_user(self):
        return db.session.query(User).filter_by(username=self.username.data).first()


class RegisterForm(Form):
    username = StringField('Username',
                            validators=[DataRequired(), Length(min=3, max=40)])
    email = StringField('Email',validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField('Password',
                            validators=[DataRequired(), Length(min=6, max=25)])
    confirm = PasswordField('Confirm password', validators=[DataRequired(),
                    EqualTo('password', message='Passwords must match.')])

easy_flask/data/project/__init__.py
# project/__init__.py

easy_flask/data/project/server/__init__.py
# project/server/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template, session, request
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_babelex import Babel


################
#### config ####
################

app = Flask(
    __name__,
    template_folder='../client/templates',
    static_folder='../client/static'
)


app_settings = os.getenv('APP_SETTINGS', 'project.server.config.DevelopmentConfig')
app.config.from_object(app_settings)


####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
toolbar = DebugToolbarExtension(app)
bootstrap = Bootstrap(app)
db = SQLAlchemy(app)
babel = Babel(app)

###################
### blueprints ####
###################

from project.server.user.views import user_blueprint
from project.server.main.views import main_blueprint
from project.server.admin import admin_blueprint
app.register_blueprint(user_blueprint)
app.register_blueprint(main_blueprint)
app.register_blueprint(admin_blueprint)

###################
### flask-babel ###
###################

@babel.localeselector
def get_locale():
    override = request.args.get('lang')

    if override:
        session['lang'] = override

    return session.get('lang', 'en')

###################
### flask-login ###
###################

from project.server.models import User

login_manager.login_view = "user_model.login"
login_manager.login_message_category = 'danger'


@login_manager.user_loader
def load_user(user_id):
    try:
        return User.query.filter(User.id == int(user_id)).first()
    except:
        return None

########################
#### error handlers ####
########################

@app.errorhandler(401)
def forbidden_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

easy_flask/data/project/server/main/__init__.py
# project/server/main/__init__.py

easy_flask/data/project/server/main/views.py
# project/server/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################


@main_blueprint.route('/')
def home():
    return render_template('main/home.html')


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")

easy_flask/data/project/server/user/__init__.py
# project/server/user/__init__.py

easy_flask/data/project/server/user/views.py
# project/server/user/views.py


#################
#### imports ####
#################

import datetime
from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, login_required

from project.server import bcrypt, db
from project.server.models import User
from project.server.user.forms import LoginForm, RegisterForm

################
#### config ####
################

user_blueprint = Blueprint('user_model', __name__,)


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Thank you for registering.', 'success')
        return redirect(url_for("user_model.members"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            user.last_login = datetime.datetime.utcnow()
            db.session.commit()

            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('user_model.members'))
        else:
            flash('Invalid username and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/members')
@login_required
def members():
    return render_template('user/members.html')

easy_flask/data/utils/__init__.py
from .colors import colors

easy_flask/data/project/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Flask Skeleton{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}


    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dissmissable">
              <a class="close" aria-label="close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}


        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block js %}{% endblock %}

  </body>
</html>

easy_flask/data/project/client/templates/footer.html
<footer>
  <div class="container">
    <small>
      <span>© <a href="mailto:michael@realpython.com">Real Python</a></span>
    </small>
  </div>
</footer>

easy_flask/data/project/client/templates/header.html
<header class="site-header">
  <!-- Navigation -->
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="{{ url_for('main.home') }}">Flask-Skeleton</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('main.about') }}">About</a></li>
          {% if current_user.is_authenticated %}
           <li><a href="{{ url_for('user_model.members') }}">Members</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('user_model.logout') }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          {% else %}
            <li><a href="{{ url_for('user_model.register') }}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
            <li><a href="{{ url_for('user_model.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Login</a></li>
          {% endif %}
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
</header>

easy_flask/data/project/client/templates/main/about.html
{% extends "_base.html" %}

{% block content %}

<div class="body-content">
  <div class="row">
    <h1>About</h1>
  </div>
</div>

{% endblock %}

easy_flask/data/project/client/templates/main/home.html
{% extends "_base.html" %}

{% block content %}

<div class="body-content">
  <div class="row">
    <h1>Welcome!</h1>
  </div>
</div>

{% endblock %}

easy_flask/data/project/client/templates/user/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Please login</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      {{ wtf.form_field(form.username) }}
      {{ wtf.form_field(form.password) }}

      <button class="btn btn-success" type="submit">Sign In!</button>
      <br><br>
      <p>Need to <a href="{{ url_for('user_model.register') }}">Register</a>?</p>
    </div>

  </form>


{% endblock content %}

easy_flask/data/project/client/templates/user/members.html
{% extends "_base.html" %}
{% block content %}
  <h1>Welcome, <em>{{ current_user.username }}</em>!</h1>
  <h3>This is the members-only page.</h3>
{% endblock %}

easy_flask/data/project/client/templates/user/register.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Please Register</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      {{ wtf.form_field(form.username) }}
      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.confirm) }}

      <button class="btn btn-success" type="submit">Register!</button>
      <br><br>
      <p>Already have an account? <a href="{{ url_for('user_model.login') }}">Sign in</a>.</p>

    </div>

  </form>


{% endblock content %}